# Generated by Django 3.2.17 on 2023-10-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=12)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='member',
        ),
    ]
